### PR TITLE
Add filtered clients notification

### PR DESCRIPTION
**Pull request by dariuskramer**
See #1033 in Redmine

### CODE REVIEW

**Review by bmalynovytch — CHANGES_REQUESTED** [review]
@dkrmr your modifications are smart 👌 although it would be better to add a selector to choose between short and long outputs (which means restoring the old code and add conditions).
Filtering is neet 👍

**Review by bmalynovytch — CHANGES_REQUESTED** [review]
On the first line of short log, replace project in brackets by project + pipe and move author to the end of the line.

**Comment by dariuskramer** [comment]
Request changes:
* Do not display description field
* Display not wanted field as title only.

**Comment by bmalynovytch** [comment]
Horizontal rule isn't very nice, maybe should you place all the content in the attachement (without header), which would also delimit the notifications.

**Review by bmalynovytch — APPROVED** [review]

**Pull request merged**
